FROM opensuse/tumbleweed

RUN zypper --gpg-auto-import-keys refresh
RUN zypper install -y openssh vim iputils ruby4.0 ruby4.0-devel ruby4.0-rubygem-cheetah ruby4.0-rubygem-nokogiri
RUN gem install git_diff_parser dry-cli

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
